# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Hedvig_Hemuppgift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hedvig_Hemuppgift


  target 'Hedvig_HemuppgiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Hedvig_HemuppgiftUITests' do
    # Pods for testing
  end

end
